#!/bin/bash

# This script expects all <app_label>-api.json files to exist in the plugins root directory.
# It produces a <app_label>-ruby-client.tar file in the plugins root directory.

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulp_nuget' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -mveuo pipefail

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

pushd ../pulp-openapi-generator
rm -rf "pulp_nuget-client"

./gen-client.sh "../pulp_nuget/nuget-api.json" "nuget" ruby "pulp_nuget"

pushd pulp_nuget-client
gem build pulp_nuget_client
tar cvf "../../pulp_nuget/nuget-ruby-client.tar" "./pulp_nuget_client-"*".gem"
popd
popd
