# Generated by Django 5.2.16 on 2026-07-14 21:39

import django.db.models.deletion
import pulpcore.app.util
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Oldest core migration compatible with our declared pulpcore lower bound.
        ('core', '0127_remove_upstreampulp_pulp_label_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='NugetDistribution',
            fields=[
                ('distribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.distribution')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.distribution',),
        ),
        migrations.CreateModel(
            name='NugetRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.remote')),
                ('includes', models.JSONField(default=list)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.remote',),
        ),
        migrations.CreateModel(
            name='NugetRepository',
            fields=[
                ('repository_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.repository')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.repository',),
        ),
        migrations.CreateModel(
            name='NugetPackageContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content')),
                ('package_id_lower', models.CharField(max_length=128)),
                ('version_normalized', models.CharField(max_length=128)),
                ('package_id', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('authors', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('title', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='')),
                ('project_url', models.TextField(blank=True, default='')),
                ('icon_url', models.TextField(blank=True, default='')),
                ('license_expression', models.TextField(blank=True, default='')),
                ('license_file', models.TextField(blank=True, default='')),
                ('license_url', models.TextField(blank=True, default='')),
                ('require_license_acceptance', models.BooleanField(default=False)),
                ('min_client_version', models.CharField(blank=True, default='', max_length=64)),
                ('dependency_groups', models.JSONField(blank=True, default=list)),
                ('_pulp_domain', models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('package_id_lower', 'version_normalized', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
    ]
