# Generated by Django 5.2.16 on 2026-07-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nugetpackagecontent',
            name='listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nugetpackagecontent',
            name='package_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
