# Generated by Django 5.2.16 on 2026-07-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuget', '0002_nugetpackagecontent_listed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nugetdistribution',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('publish_nugetdistribution', "Can push, unlist, and relist packages via the distribution's publish endpoint"), ('manage_roles_nugetdistribution', 'Can manage roles on nuget distributions')]},
        ),
        migrations.AlterModelOptions(
            name='nugetremote',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('manage_roles_nugetremote', 'Can manage roles on nuget remotes')]},
        ),
        migrations.AlterModelOptions(
            name='nugetrepository',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('sync_nugetrepository', 'Can start a sync task'), ('modify_nugetrepository', 'Can modify content of the repository'), ('manage_roles_nugetrepository', 'Can manage roles on nuget repositories'), ('repair_nugetrepository', 'Can repair repository versions')]},
        ),
    ]
