# Generated by Django 5.2.16 on 2026-07-15 07:10

import django.db.models.deletion
import pulpcore.app.models.access_policy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_taskschedule_pulp_domain_alter_taskschedule_name_and_more'),
        ('nuget', '0003_alter_nugetdistribution_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NugetContentGuard',
            fields=[
                ('contentguard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contentguard')),
            ],
            options={
                'permissions': [('download_nugetcontentguard', 'Can download content protected by this guard'), ('manage_roles_nugetcontentguard', 'Can manage roles on nuget content guards')],
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.contentguard', pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
    ]
