# Generated by Django 5.2.16 on 2026-07-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuget', '0004_nugetcontentguard'),
    ]

    operations = [
        migrations.AddField(
            model_name='nugetremote',
            name='excludes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='nugetrepository',
            name='last_sync_details',
            field=models.JSONField(default=dict),
        ),
    ]
