# Generated by Django 5.2.16 on 2026-07-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuget', '0005_nugetremote_excludes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nugetpackagecontent',
            name='icon_file',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nugetpackagecontent',
            name='readme_file',
            field=models.TextField(blank=True, default=''),
        ),
    ]
