# Generated by Django 5.2.16 on 2026-07-16 23:13

import django.db.models.deletion
import pulpcore.app.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Repinned from the dev checkout's 0153 (unreleased): 0127 is the newest core
        # migration guaranteed to exist at our declared pulpcore floor.
        ('core', '0127_remove_upstreampulp_pulp_label_select'),
        ('nuget', '0006_nugetpackagecontent_icon_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NugetSymbolPackageContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content')),
                ('package_id_lower', models.CharField(max_length=128)),
                ('version_normalized', models.CharField(max_length=128)),
                ('package_id', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('pdb_files', models.JSONField(blank=True, default=list)),
                ('_pulp_domain', models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('package_id_lower', 'version_normalized', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
    ]
