# Generated by Django 5.2.16 on 2026-07-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuget', '0007_nugetsymbolpackagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='nugetrepository',
            name='retain_package_versions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
